version: '2'

services:

  neo4j:
    build: ./neo4j
    ports:
      - 7474
      - 7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes: 
      - ./neo4j/data:/var/lib/neo4j/data
    restart: always

  api:
    build: ./api
    ports:
      - 4000:4000
    links:
    - neo4j
    depends_on:
    - neo4j
    restart: always

  elasticsearch:
    build: es
    volumes:
        - ./es/esdata:/usr/share/elasticsearch/data 
    ports:
        - 9200:9200
    expose:
        - 9300
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    environment:
        - "ES_JAVA_OPTS=-Xms400m -Xmx400m"
        - bootstrap.memory_lock=true
        - cluster.routing.allocation.disk.threshold_enabled=false
        - discovery.type=single-node
        - http.cors.enabled=true
        - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
    hostname: elasticsearch
    mem_limit: 1250m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  elasticsearch-head:
    build: head
    ports:
      - "9100:9100"
    depends_on:
      - elasticsearch
#  ui:
#    build: ./ui
#    ports:
#      - 3000:3000
#    links:
#    - api
#    depends_on:
#    - api
